// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_back_produktevaluering.web.Models;

namespace web_back_produktevaluering.web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("web_back_produktevaluering.web.Models.Evaluering", b =>
                {
                    b.Property<int>("EvalueringId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Karakter");

                    b.Property<string>("Navn")
                        .IsRequired();

                    b.Property<string>("Produkt")
                        .IsRequired();

                    b.HasKey("EvalueringId");

                    b.ToTable("Evalueringer");
                });
#pragma warning restore 612, 618
        }
    }
}
